import sqlite3

# Connect to database
conn = sqlite3.connect("college.db")

cursor = conn.cursor()

# SQL generated by LLM
sql = "SELECT name, department FROM students WHERE marks > 80"

# Execute SQL
cursor.execute(sql)

# Get results
results = cursor.fetchall()

print("Query Results:")
print()

for row in results:
    print(row)

conn.close()